const MovieConstants = {
  POPULAR_MOVIES_RECEIVED: "POPULAR_MOVIES_RECEIVED",
  RECOMMENDED_MOVIES_RECEIVED: "RECOMMENDED_MOVIES_RECEIVED",
  MOVIE_INFO_RECEIVED: "MOVIE_INFO_RECEIVED"
};

module.exports = MovieConstants;
