const MovieConstants = {
  MOVIES_RECEIVED: "MOVIES_RECEIVED",
  POPULAR_MOVIES_RECEIVED: "POPULAR_MOVIES_RECEIVED",
  RECOMMENDED_MOVIES_RECEIVED: "RECOMMENDED_MOVIES_RECEIVED",
  MOVIE_INFO_RECEIVED: "MOVIE_INFO_RECEIVED",
  MOVIE_RATING_RECEIVED: "MOVIE_RATING_RECEIVED",
  MOVIE_RATINGS_RECEIVED: "MOVIE_RATINGS_RECEIVED",
  SKIP_MOVIE: "SKIP_MOVIE",
  MARK_NOT_INTERESTED: "MARK_NOT_INTERESTED",
  MOVIE_RATINGS_DELETED: "MOVIE_RATINGS_DELETED",
  RECOMMENDATIONS_DELETED: "RECOMMENDATIONS_DELETED",
  TRAILER_RECEIVED: "Store received movie trailer"
};

module.exports = MovieConstants;
